server_info:
  address: "http://127.0.0.1:8000"
  passphrase:
    - "123456"
    - "123457"
  specification:
    input:
      - image
      # - text
    output:
      # - list
      - image
      - text
      # - json
  name: "test app"
  invitation_message: "send image"
port: 8000
storage:
  files:
    path: './tmp_storage'
# consul:
#   host: 127.0.0.1
#   port: 8500
ds_model_config:
  model_path: '/Users/sergey/work/dbrain/programming/wrappa/wrappa/dummy/ds_one.py'
  # model_path: '/Users/sergey/work/dbrain/programming/wrappa/wrappa/dummy/ds_legacy.py'
  # model_path: '/Users/sergey/work/dbrain/programming/wrappa/wrappa/dummy/raising_model.py'
  config: {}
