server_info:
  address: "http://localhost:8000"
  specification:
    input: image
    output: image
  name: "test app"
  invitation_message: "send image"
port: 8000
ds_model_config:
  model_path: '/Users/sergey/work/dbrain/programming/dbrain-ds-server-wrapper/dbrdsw/dummy/ds.py'
  config: {}
